language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
sudo: false
before_script:
- composer self-update
- composer install --prefer-dist --no-interaction
